updated backup script

diff --git a/mk/iks/adm/cron/backup b/mk/iks/adm/cron/backup
--- a/mk/iks/adm/cron/backup
+++ b/mk/iks/adm/cron/backup
@@ -13,11 +13,13 @@ GTM_DIR=/usr/gtm
 GTM_DATA_DIR=$GTM_DIR/data
 GTM_DATA_MJL_DIR=$GTM_DIR/data/mjl
 GTM_BACKUP_DIR=/mnt/backup
+GTM_BACKUP_SHARE_DIR=/mnt/backup_share
 
 if ! test -d $GTM_DIR; then logger $TAG "Directory $GTM_DIR not found"; exit 1; fi
 if ! test -d $GTM_DATA_DIR; then logger $TAG "Directory $GTM_DATA_DIR not found"; exit 1; fi
 if ! test -d $GTM_DATA_MJL_DIR; then logger $TAG "Directory $GTM_DATA_MJL_DIR not found"; exit 1; fi
 if ! test -d $GTM_BACKUP_DIR; then logger $TAG "Directory $GTM_BACKUP_DIR not found"; exit 1; fi
+if ! test -d $GTM_BACKUP_SHARE_DIR; then logger $TAG "Directory $GTM_BACKUP_SHARE_DIR not found"; exit 1; fi
 
 PROG=$(basename $0)
 DEBUG=$(mktemp --tmpdir --suffix=.debug $PROG.XXX)
@@ -31,10 +33,11 @@ exec 2>&1
 
 enough_space() {
   local free_space_size
-  local required_size
+  local dir=$1
+  local required_size=$2
+  
 
-  free_space_size=`stat -f $GTM_BACKUP_DIR -c "%s * %a" | bc`
-  required_size=$1
+  free_space_size=`stat -f $dir -c "%s * %a" | bc`
   test $free_space_size -gt $required_size
 }
 
@@ -58,19 +61,20 @@ database_size() {
 #
 
 enshure_space() {
-  local required_size=$1
+  local dir=$1 
+  local required_size=$2
   local count=2
   local ret=0
-  if ! enough_space $required_size; then
+  if ! enough_space $dir $required_size ; then
     ret=1
     while [ $count -ne 0 ]; do
-      nbackup=$(find $GTM_BACKUP_DIR/ -mindepth 1 -maxdepth 1 -type -d -name "iks_*" | wc -l)
+      nbackup=$(find $dir/ -mindepth 1 -maxdepth 1 -type -d -name "iks_*" | wc -l)
       # At least 3 last backups should exists
       if [ $nbackup -gt 3 ]; then
         # find oldest backup 
-        oldest_backup=$(find $GTM_BACKUP_DIR/ -mindepth 1 -maxdepth 1 -type d -name "iks_*" | sort | head -n 1)
+        oldest_backup=$(find $dir/ -mindepth 1 -maxdepth 1 -type d -name "iks_*" | sort | head -n 1)
         rm -vr $oldest_backup
-        if enough_space $required_size; then 
+        if enough_space $dir $required_size; then 
           ret=0;
           break;
         fi
@@ -88,17 +92,11 @@ enshure_space() {
 # Start backup procedure
 #
 
-# Ensure we have nfs share mounted to $GTM_BACKUP_DIR
-if [ "x$(findmnt $GTM_BACKUP_DIR -n -t nfs -o FSTYPE)" != "xnfs" ]; then
-  logger -t $TAG "ERROR: Nfs share is not mounted to ${GTM_BACKUP_DIR}. Exit."
-  exit 1
-fi
-
 CURRENT_BACKUP_DIR=$GTM_BACKUP_DIR/iks_$(date +%Y-%m-%d_%H-%M-%S)
 # Create directory and grant permissions
 mkdir -vp $CURRENT_BACKUP_DIR && chown -v gtm:gtm $CURRENT_BACKUP_DIR && chmod -v 775 $CURRENT_BACKUP_DIR
 if test $? -ne 0; then
-  logger -t $TAG "ERROR: Cannot create ${CURRENT_BACKUP_DIR}. Exit."
+  logger -t $TAG "ERROR: Cannot create $CURRENT_BACKUP_DIR. Exit."
   exit 1
 fi
 
@@ -133,8 +131,8 @@ journals_size=$(du -scb --files0-from=$GTM_BACKUP_JOURNALS_LIST | tail -n 1 | cu
 #
 required_size=$(expr $db_size + $gtmdir_size + $iks_r_size + $lib_r_size + $journals_size)
 
-if ! enough_space $required_size; then
-  if ! enshure_space $required_size; then
+if ! enough_space $GTM_BACKUP_DIR $required_size; then
+  if ! enshure_space $GTM_BACKUP_DIR $required_size; then
     logger -t $TAG "ERROR: Cannot ensure space for backup. Exit."
     exit 1
   fi
@@ -147,7 +145,7 @@ status=0
 # Backup $GTM_DIR
 # 
 
-logger -t $TAG "INFO: Start new backup. Current backup dir is ${CURRENT_BACKUP_DIR}."
+logger -t $TAG "INFO: Start new backup. Current backup dir is $CURRENT_BACKUP_DIR."
 logger -t $TAG "INFO: Start $GTM_DIR backup without .dat and journal files."
 
 IFS_ORIG=$IFS
@@ -231,3 +229,32 @@ logger -t $TAG "INFO: Backup procedure completed."
 
 # Save debug info
 mv -v $DEBUG $CURRENT_BACKUP_DIR/
+
+#
+# Start moving backup from local device to nfs share
+#
+
+# Ensure we have a device mounted to $GTM_BACKUP_SHARE_DIR
+if ! findmnt -n --real -O rw $GTM_BACKUP_SHARE_DIR > /dev/null; then
+  logger -t $TAG "ERROR: Device is not mounted to $GTM_BACKUP_SHARE_DIR"
+  exit 1
+fi
+
+# Ensure we have nfs share mounted to $GTM_BACKUP_DIR
+#if [ "x$(findmnt $GTM_BACKUP_DIR -n -t nfs -o FSTYPE)" != "xnfs" ]; then
+#  logger -t $TAG "ERROR: Nfs share is not mounted to ${GTM_BACKUP_DIR}. Exit."
+#  exit 1
+#fi
+
+if ! enough_space $GTM_BACKUP_SHARE_DIR $required_size; then
+  if ! enshure_space $GTM_BACKUP_SHARE_DIR $required_size; then
+    logger -t $TAG "ERROR: Cannot ensure space for $GTM_BACKUP_SHARE_DIR. Exit."
+    exit 1
+  fi
+fi
+
+if ! cp -vRa $CURRENT_BACKUP_DIR $GTM_BACKUP_SHARE_DIR/; then
+  logger -t $TAG "ERROR: Moving $CURRENT_BACKUP_DIR from local storage to nfs share completed with errors."
+else
+  logger -t $TAG "INFO: Moving $CURRENT_BACKUP_DIR from local storage to nfs share completed succesfully."
+fi
